ARG RACKET_IMAGE

FROM ${RACKET_IMAGE}

RUN raco pkg install --auto --installation \
    distro-build \
    distro-build-test \
    main-distribution \
    main-distribution-test

COPY ./test.sh /usr/bin/racket-tests.sh
RUN chmod +x /usr/bin/racket-tests.sh
CMD ["/bin/sh", "-c", "/usr/bin/racket-tests.sh"]
