ARG RACKET_IMAGE

FROM ${RACKET_IMAGE}

RUN raco pkg install --auto --installation --skip-installed \
    distro-build \
    distro-build-test \
    main-distribution \
    main-distribution-test \
    raco-find-collection \
    https://github.com/racket/pcps-test.git

COPY ./test.sh /usr/bin/racket-tests.sh
RUN chmod +x /usr/bin/racket-tests.sh
RUN groupadd -r racket && useradd --no-log-init -r -g racket racket
CMD ["/bin/sh", "-c", "/usr/bin/racket-tests.sh"]
