FROM ubuntu:17.10
ARG version="6.10.1.900"

# Setup

RUN apt-get update
RUN apt-get install -y wget

# Test the regular installer

RUN wget http://pre-release.racket-lang.org/installers/racket-$version-x86_64-linux.sh

RUN sh ./racket-$version-x86_64-linux.sh --in-place --dest ./racket-in-place

RUN ./racket-in-place/bin/raco pkg install --auto racket-test htdp-test typed-racket-test

# robby
RUN ./racket-in-place/bin/racket -l tests/racket/contract/all
RUN ./racket-in-place/bin/racket -l tests/racket/contract-stress-argmin
RUN ./racket-in-place/bin/racket -l tests/racket/contract-stress-take-right

# samth
RUN apt-get install -y glib-2.0
RUN apt-get install -y xvfb
RUN ./racket-in-place/bin/raco test -l tests/match/main
RUN xvfb-run ./racket-in-place/bin/racket -l typed-racket-test -- --all

# ryanc
RUN ./racket-in-place/bin/raco pkg install data-test db-test srfi-test
RUN ./racket-in-place/bin/raco test -c tests/stxparse
RUN ./racket-in-place/bin/raco test -c tests/data
RUN ./racket-in-place/bin/racket -l tests/db/all-tests
RUN ./racket-in-place/bin/racket -l tests/srfi/run-tests


# sstrickl
RUN ./racket-in-place/bin/raco test -l tests/units/test-unit-contracts
RUN ./racket-in-place/bin/racket -l tests/racket/contract/define-contract
RUN ./racket-in-place/bin/racket -l tests/racket/contract/with-contract
RUN ./racket-in-place/bin/racket -l tests/racket/contract/class

# stchang
RUN ./racket-in-place/bin/raco test -l lazy/tests/main.rkt

# dvanhorn
RUN ./racket-in-place/bin/raco test -c eopl/tests


# stchang # currently fails because of check-random, fix is on master
#RUN ./racket-in-place/bin/raco test -l tests/stepper/automatic-tests.rkt

# jay

RUN ./racket-in-place/bin/raco test -c datalog/tests
RUN ./racket-in-place/bin/raco test -c racklog/tests
RUN xvfb-run ./racket-in-place/bin/raco test -c plai
RUN ./racket-in-place/bin/raco pkg install html-test 
RUN ./racket-in-place/bin/raco test -c tests/html
RUN xvfb-run ./racket-in-place/bin/raco test -c tests/xml

# ryanc
# fails due to the same failures seen on drdr
#RUN ./racket-in-place/bin/raco test -l tests/macro-debugger/all-tests.rkt

# mflatt
RUN apt-get install -y gcc
RUN ./racket-in-place/bin/raco pkg install compiler-test
# fails with something about -fPIC
#RUN ./racket-in-place/bin/racket -l tests/racket/embed-in-c
# fails with missing collection that does seem to be there
#RUN ./racket-in-place/bin/racket -l tests/compiler/embed/test

# robby
RUN xvfb-run ./racket-in-place/bin/racket -l 2htdp/tests/bitmap-as-image-in-universe
RUN xvfb-run ./racket-in-place/bin/racket -l 2htdp/tests/image-equality-performance-htdp
RUN xvfb-run ./racket-in-place/bin/racket -l 2htdp/tests/image-equality-performance
RUN xvfb-run ./racket-in-place/bin/racket -l 2htdp/tests/image-too-large
RUN xvfb-run ./racket-in-place/bin/racket -l 2htdp/tests/test-image
RUN ./racket-in-place/bin/raco pkg install redex-test
# fails due to font & rendering differences
#RUN xvfb-run ./racket-in-place/bin/racket -l redex/tests/run-tests

RUN ./racket-in-place/bin/raco pkg install planet-test
RUN ./racket-in-place/bin/raco test -l tests/planet/run-all

# mflatt
RUN ./racket-in-place/bin/raco pkg install --auto distro-build
RUN ./racket-in-place/bin/raco pkg install --auto --name distro-build-test https://github.com/racket/distro-build.git?path=distro-build-test
# fails with an error about #f being passed to `system*`
# RUN ./racket-in-place/bin/racket -l distro-build/tests/unix-installer

RUN ./racket-in-place/bin/raco pkg install --auto raco-find-collection
# FIXME install everything in installation scope
RUN ./racket-in-place/bin/racket -f root/.racket/$version/pkgs/racket-test-core/tests/racket/pack.rktl
# fails with a strange error about files not found, i suspect weird current-dir
#RUN ./racket-in-place/bin/racket -l tests/htdp-lang/test-htdp
RUN ./racket-in-place/bin/raco pkg install -i --auto gui-test
RUN mkdir test-dir
WORKDIR test-dir
RUN xvfb-run ../racket-in-place/bin/racket -l tests/gracket/test
RUN xvfb-run ../racket-in-place/bin/gracket -z -e 1
RUN xvfb-run ../racket-in-place/bin/gracket -e 1