ARG RACKET_TEST_IMAGE

FROM ${RACKET_TEST_IMAGE}

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgtk2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY ./test-gui.sh /usr/bin/racket-gui-tests.sh
RUN chmod +x /usr/bin/racket-gui-tests.sh
CMD ["/bin/sh", "-c", "/usr/bin/racket-gui-tests.sh"]
