ARG RACKET_IMAGE

FROM ${RACKET_IMAGE}

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgtk2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN raco pkg install --auto --installation --skip-installed \
    distro-build \
    distro-build-test \
    main-distribution \
    main-distribution-test \
    raco-find-collection \
    https://github.com/racket/pcps-test.git

RUN groupadd -r racket \
 && useradd --no-log-init -r -g racket racket \
 && chown -R racket:racket ${RACKET_DIRS}

COPY ./suite-failing.sh /usr/bin/suite-failing
COPY ./suite-gui.sh /usr/bin/suite-gui
COPY ./suite-nogui.sh /usr/bin/suite-nogui
RUN chmod +x /usr/bin/suite-failing
RUN chmod +x /usr/bin/suite-gui
RUN chmod +x /usr/bin/suite-nogui

USER racket:racket
