ARG DOCKER_COMPOSE_IMAGE

FROM ${DOCKER_COMPOSE_IMAGE}

RUN mkdir /etc/racket-test-runner
COPY ./docker-compose.yml /etc/racket-test-runner/docker-compose.yml
COPY ./Dockerfile.test /etc/racket-test-runner/Dockerfile.test
COPY ./suite-failing.sh /etc/racket-test-runner/suite-failing.sh
COPY ./suite-gui.sh /etc/racket-test-runner/suite-gui.sh
COPY ./suite-nogui.sh /etc/racket-test-runner/suite-nogui.sh

COPY ./test-runner.sh /usr/bin/racket-test-runner
RUN chmod +x /usr/bin/racket-test-runner
ENTRYPOINT ["racket-test-runner"]
