ARG DOCKER_COMPOSE_IMAGE

FROM ${DOCKER_COMPOSE_IMAGE}

RUN mkdir /etc/racket-installer
COPY ./docker-compose.yml /etc/racket-installer/docker-compose.yml
COPY ./Dockerfile.script-inplace /etc/racket-installer/Dockerfile.script-inplace

COPY ./installer.sh /usr/bin/racket-installer
RUN chmod +x /usr/bin/racket-installer
ENTRYPOINT ["racket-installer"]
